package com.groundmarkervariables.variables;

import java.util.Locale;
import java.util.Map;

// Ported from RuneLite's ChatCommandsPlugin#longBossName (BSD 2-Clause License):
// Copyright (c) 2017, Adam <Adam@sigterm.info>. All rights reserved.
// See https://github.com/runelite/runelite/blob/master/LICENSE
//
// Resolves a short alias (e.g. "cg", "cox cm 3") to the canonical name
// BossKillCountTracker stores kill counts under; unmatched text is title-cased instead, same
// as longBossName's own default case. Used to normalize {kc <boss>}'s lookup only — not
// offered as an autocomplete candidate list (see AdvancedLabelEditor#completeBossName).
final class BossAliases
{
	private static final Map<String, String> ALIASES = Map.ofEntries(
		Map.entry("corp", "Corporeal Beast"),
		Map.entry("jad", "TzTok-Jad"),
		Map.entry("tzhaar fight cave", "TzTok-Jad"),
		Map.entry("kq", "Kalphite Queen"),
		Map.entry("chaos ele", "Chaos Elemental"),
		Map.entry("dusk", "Grotesque Guardians"),
		Map.entry("dawn", "Grotesque Guardians"),
		Map.entry("gargs", "Grotesque Guardians"),
		Map.entry("ggs", "Grotesque Guardians"),
		Map.entry("gg", "Grotesque Guardians"),
		Map.entry("crazy arch", "Crazy Archaeologist"),
		Map.entry("deranged arch", "Deranged Archaeologist"),
		Map.entry("mole", "Giant Mole"),
		Map.entry("vetion", "Vet'ion"),
		Map.entry("calvarion", "Calvar'ion"),
		Map.entry("calv", "Calvar'ion"),
		Map.entry("vene", "Venenatis"),
		Map.entry("kbd", "King Black Dragon"),
		Map.entry("vork", "Vorkath"),
		Map.entry("sire", "Abyssal Sire"),
		Map.entry("smoke devil", "Thermonuclear Smoke Devil"),
		Map.entry("thermy", "Thermonuclear Smoke Devil"),
		Map.entry("cerb", "Cerberus"),
		Map.entry("zuk", "TzKal-Zuk"),
		Map.entry("inferno", "TzKal-Zuk"),
		Map.entry("hydra", "Alchemical Hydra"),
		Map.entry("sara", "Commander Zilyana"),
		Map.entry("saradomin", "Commander Zilyana"),
		Map.entry("zilyana", "Commander Zilyana"),
		Map.entry("zily", "Commander Zilyana"),
		Map.entry("zammy", "K'ril Tsutsaroth"),
		Map.entry("zamorak", "K'ril Tsutsaroth"),
		Map.entry("kril", "K'ril Tsutsaroth"),
		Map.entry("kril tsutsaroth", "K'ril Tsutsaroth"),
		Map.entry("arma", "Kree'arra"),
		Map.entry("kree", "Kree'arra"),
		Map.entry("kreearra", "Kree'arra"),
		Map.entry("armadyl", "Kree'arra"),
		Map.entry("bando", "General Graardor"),
		Map.entry("bandos", "General Graardor"),
		Map.entry("graardor", "General Graardor"),
		Map.entry("supreme", "Dagannoth Supreme"),
		Map.entry("rex", "Dagannoth Rex"),
		Map.entry("prime", "Dagannoth Prime"),
		Map.entry("wt", "Wintertodt"),
		Map.entry("barrows", "Barrows Chests"),
		Map.entry("herbi", "Herbiboar"),
		Map.entry("cox", "Chambers of Xeric"),
		Map.entry("xeric", "Chambers of Xeric"),
		Map.entry("chambers", "Chambers of Xeric"),
		Map.entry("olm", "Chambers of Xeric"),
		Map.entry("raids", "Chambers of Xeric"),
		Map.entry("cox 1", "Chambers of Xeric Solo"),
		Map.entry("cox solo", "Chambers of Xeric Solo"),
		Map.entry("cox 2", "Chambers of Xeric 2 players"),
		Map.entry("cox duo", "Chambers of Xeric 2 players"),
		Map.entry("cox 3", "Chambers of Xeric 3 players"),
		Map.entry("cox 4", "Chambers of Xeric 4 players"),
		Map.entry("cox 5", "Chambers of Xeric 5 players"),
		Map.entry("cox 6", "Chambers of Xeric 6 players"),
		Map.entry("cox 7", "Chambers of Xeric 7 players"),
		Map.entry("cox 8", "Chambers of Xeric 8 players"),
		Map.entry("cox 9", "Chambers of Xeric 9 players"),
		Map.entry("cox 10", "Chambers of Xeric 10 players"),
		Map.entry("cox 11-15", "Chambers of Xeric 11-15 players"),
		Map.entry("cox 11", "Chambers of Xeric 11-15 players"),
		Map.entry("cox 12", "Chambers of Xeric 11-15 players"),
		Map.entry("cox 13", "Chambers of Xeric 11-15 players"),
		Map.entry("cox 14", "Chambers of Xeric 11-15 players"),
		Map.entry("cox 15", "Chambers of Xeric 11-15 players"),
		Map.entry("cox 16-23", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 16", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 17", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 18", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 19", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 20", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 21", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 22", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 23", "Chambers of Xeric 16-23 players"),
		Map.entry("cox 24", "Chambers of Xeric 24+ players"),
		Map.entry("cox 24+", "Chambers of Xeric 24+ players"),
		Map.entry("chambers of xeric: challenge mode", "Chambers of Xeric Challenge Mode"),
		Map.entry("cox cm", "Chambers of Xeric Challenge Mode"),
		Map.entry("xeric cm", "Chambers of Xeric Challenge Mode"),
		Map.entry("chambers cm", "Chambers of Xeric Challenge Mode"),
		Map.entry("olm cm", "Chambers of Xeric Challenge Mode"),
		Map.entry("raids cm", "Chambers of Xeric Challenge Mode"),
		Map.entry("chambers of xeric - challenge mode", "Chambers of Xeric Challenge Mode"),
		Map.entry("cox cm 1", "Chambers of Xeric Challenge Mode Solo"),
		Map.entry("cox cm solo", "Chambers of Xeric Challenge Mode Solo"),
		Map.entry("cox cm 2", "Chambers of Xeric Challenge Mode 2 players"),
		Map.entry("cox cm duo", "Chambers of Xeric Challenge Mode 2 players"),
		Map.entry("cox cm 3", "Chambers of Xeric Challenge Mode 3 players"),
		Map.entry("cox cm 4", "Chambers of Xeric Challenge Mode 4 players"),
		Map.entry("cox cm 5", "Chambers of Xeric Challenge Mode 5 players"),
		Map.entry("cox cm 6", "Chambers of Xeric Challenge Mode 6 players"),
		Map.entry("cox cm 7", "Chambers of Xeric Challenge Mode 7 players"),
		Map.entry("cox cm 8", "Chambers of Xeric Challenge Mode 8 players"),
		Map.entry("cox cm 9", "Chambers of Xeric Challenge Mode 9 players"),
		Map.entry("cox cm 10", "Chambers of Xeric Challenge Mode 10 players"),
		Map.entry("cox cm 11-15", "Chambers of Xeric Challenge Mode 11-15 players"),
		Map.entry("cox cm 11", "Chambers of Xeric Challenge Mode 11-15 players"),
		Map.entry("cox cm 12", "Chambers of Xeric Challenge Mode 11-15 players"),
		Map.entry("cox cm 13", "Chambers of Xeric Challenge Mode 11-15 players"),
		Map.entry("cox cm 14", "Chambers of Xeric Challenge Mode 11-15 players"),
		Map.entry("cox cm 15", "Chambers of Xeric Challenge Mode 11-15 players"),
		Map.entry("cox cm 16-23", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 16", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 17", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 18", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 19", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 20", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 21", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 22", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 23", "Chambers of Xeric Challenge Mode 16-23 players"),
		Map.entry("cox cm 24", "Chambers of Xeric Challenge Mode 24+ players"),
		Map.entry("cox cm 24+", "Chambers of Xeric Challenge Mode 24+ players"),
		Map.entry("tob", "Theatre of Blood"),
		Map.entry("theatre", "Theatre of Blood"),
		Map.entry("verzik", "Theatre of Blood"),
		Map.entry("verzik vitur", "Theatre of Blood"),
		Map.entry("raids 2", "Theatre of Blood"),
		Map.entry("tob 1", "Theatre of Blood Solo"),
		Map.entry("tob solo", "Theatre of Blood Solo"),
		Map.entry("tob 2", "Theatre of Blood 2 players"),
		Map.entry("tob duo", "Theatre of Blood 2 players"),
		Map.entry("tob 3", "Theatre of Blood 3 players"),
		Map.entry("tob 4", "Theatre of Blood 4 players"),
		Map.entry("tob 5", "Theatre of Blood 5 players"),
		Map.entry("theatre of blood: story mode", "Theatre of Blood Entry Mode"),
		Map.entry("tob sm", "Theatre of Blood Entry Mode"),
		Map.entry("tob story mode", "Theatre of Blood Entry Mode"),
		Map.entry("tob story", "Theatre of Blood Entry Mode"),
		Map.entry("theatre of blood: entry mode", "Theatre of Blood Entry Mode"),
		Map.entry("tob em", "Theatre of Blood Entry Mode"),
		Map.entry("tob entry mode", "Theatre of Blood Entry Mode"),
		Map.entry("tob entry", "Theatre of Blood Entry Mode"),
		Map.entry("theatre of blood: hard mode", "Theatre of Blood Hard Mode"),
		Map.entry("tob cm", "Theatre of Blood Hard Mode"),
		Map.entry("tob hm", "Theatre of Blood Hard Mode"),
		Map.entry("tob hard mode", "Theatre of Blood Hard Mode"),
		Map.entry("tob hard", "Theatre of Blood Hard Mode"),
		Map.entry("hmt", "Theatre of Blood Hard Mode"),
		Map.entry("hmt 1", "Theatre of Blood Hard Mode Solo"),
		Map.entry("hmt solo", "Theatre of Blood Hard Mode Solo"),
		Map.entry("hmt 2", "Theatre of Blood Hard Mode 2 players"),
		Map.entry("hmt duo", "Theatre of Blood Hard Mode 2 players"),
		Map.entry("hmt 3", "Theatre of Blood Hard Mode 3 players"),
		Map.entry("hmt 4", "Theatre of Blood Hard Mode 4 players"),
		Map.entry("hmt 5", "Theatre of Blood Hard Mode 5 players"),
		Map.entry("toa", "Tombs of Amascut"),
		Map.entry("tombs", "Tombs of Amascut"),
		Map.entry("amascut", "Tombs of Amascut"),
		Map.entry("warden", "Tombs of Amascut"),
		Map.entry("wardens", "Tombs of Amascut"),
		Map.entry("raids 3", "Tombs of Amascut"),
		Map.entry("toa 1", "Tombs of Amascut Solo"),
		Map.entry("toa solo", "Tombs of Amascut Solo"),
		Map.entry("toa 2", "Tombs of Amascut 2 players"),
		Map.entry("toa duo", "Tombs of Amascut 2 players"),
		Map.entry("toa 3", "Tombs of Amascut 3 players"),
		Map.entry("toa 4", "Tombs of Amascut 4 players"),
		Map.entry("toa 5", "Tombs of Amascut 5 players"),
		Map.entry("toa 6", "Tombs of Amascut 6 players"),
		Map.entry("toa 7", "Tombs of Amascut 7 players"),
		Map.entry("toa 8", "Tombs of Amascut 8 players"),
		Map.entry("toa entry", "Tombs of Amascut Entry Mode"),
		Map.entry("tombs of amascut - entry", "Tombs of Amascut Entry Mode"),
		Map.entry("toa entry mode", "Tombs of Amascut Entry Mode"),
		Map.entry("toa entry 1", "Tombs of Amascut Entry Mode Solo"),
		Map.entry("toa entry solo", "Tombs of Amascut Entry Mode Solo"),
		Map.entry("toa entry 2", "Tombs of Amascut Entry Mode 2 players"),
		Map.entry("toa entry duo", "Tombs of Amascut Entry Mode 2 players"),
		Map.entry("toa entry 3", "Tombs of Amascut Entry Mode 3 players"),
		Map.entry("toa entry 4", "Tombs of Amascut Entry Mode 4 players"),
		Map.entry("toa entry 5", "Tombs of Amascut Entry Mode 5 players"),
		Map.entry("toa entry 6", "Tombs of Amascut Entry Mode 6 players"),
		Map.entry("toa entry 7", "Tombs of Amascut Entry Mode 7 players"),
		Map.entry("toa entry 8", "Tombs of Amascut Entry Mode 8 players"),
		Map.entry("tombs of amascut: expert mode", "Tombs of Amascut Expert Mode"),
		Map.entry("toa expert", "Tombs of Amascut Expert Mode"),
		Map.entry("tombs of amascut - expert", "Tombs of Amascut Expert Mode"),
		Map.entry("toa expert mode", "Tombs of Amascut Expert Mode"),
		Map.entry("toa expert 1", "Tombs of Amascut Expert Mode Solo"),
		Map.entry("toa expert solo", "Tombs of Amascut Expert Mode Solo"),
		Map.entry("toa expert 2", "Tombs of Amascut Expert Mode 2 players"),
		Map.entry("toa expert duo", "Tombs of Amascut Expert Mode 2 players"),
		Map.entry("toa expert 3", "Tombs of Amascut Expert Mode 3 players"),
		Map.entry("toa expert 4", "Tombs of Amascut Expert Mode 4 players"),
		Map.entry("toa expert 5", "Tombs of Amascut Expert Mode 5 players"),
		Map.entry("toa expert 6", "Tombs of Amascut Expert Mode 6 players"),
		Map.entry("toa expert 7", "Tombs of Amascut Expert Mode 7 players"),
		Map.entry("toa expert 8", "Tombs of Amascut Expert Mode 8 players"),
		Map.entry("gaunt", "Gauntlet"),
		Map.entry("gauntlet", "Gauntlet"),
		Map.entry("the gauntlet", "Gauntlet"),
		Map.entry("cgaunt", "Corrupted Gauntlet"),
		Map.entry("cgauntlet", "Corrupted Gauntlet"),
		Map.entry("the corrupted gauntlet", "Corrupted Gauntlet"),
		Map.entry("cg", "Corrupted Gauntlet"),
		Map.entry("nm", "Nightmare"),
		Map.entry("tnm", "Nightmare"),
		Map.entry("nmare", "Nightmare"),
		Map.entry("the nightmare", "Nightmare"),
		Map.entry("pnm", "Phosani's Nightmare"),
		Map.entry("phosani", "Phosani's Nightmare"),
		Map.entry("phosanis", "Phosani's Nightmare"),
		Map.entry("phosani nm", "Phosani's Nightmare"),
		Map.entry("phosani nightmare", "Phosani's Nightmare"),
		Map.entry("phosanis nightmare", "Phosani's Nightmare"),
		Map.entry("hs", "Hallowed Sepulchre"),
		Map.entry("sepulchre", "Hallowed Sepulchre"),
		Map.entry("ghc", "Hallowed Sepulchre"),
		Map.entry("hs1", "Hallowed Sepulchre Floor 1"),
		Map.entry("hs 1", "Hallowed Sepulchre Floor 1"),
		Map.entry("hs2", "Hallowed Sepulchre Floor 2"),
		Map.entry("hs 2", "Hallowed Sepulchre Floor 2"),
		Map.entry("hs3", "Hallowed Sepulchre Floor 3"),
		Map.entry("hs 3", "Hallowed Sepulchre Floor 3"),
		Map.entry("hs4", "Hallowed Sepulchre Floor 4"),
		Map.entry("hs 4", "Hallowed Sepulchre Floor 4"),
		Map.entry("hs5", "Hallowed Sepulchre Floor 5"),
		Map.entry("hs 5", "Hallowed Sepulchre Floor 5"),
		Map.entry("wbac", "Colossal Wyrm Agility Course (Basic)"),
		Map.entry("cwbac", "Colossal Wyrm Agility Course (Basic)"),
		Map.entry("wyrmb", "Colossal Wyrm Agility Course (Basic)"),
		Map.entry("wyrmbasic", "Colossal Wyrm Agility Course (Basic)"),
		Map.entry("wyrm basic", "Colossal Wyrm Agility Course (Basic)"),
		Map.entry("colossal basic", "Colossal Wyrm Agility Course (Basic)"),
		Map.entry("colossal wyrm basic", "Colossal Wyrm Agility Course (Basic)"),
		Map.entry("waac", "Colossal Wyrm Agility Course (Advanced)"),
		Map.entry("cwaac", "Colossal Wyrm Agility Course (Advanced)"),
		Map.entry("wyrma", "Colossal Wyrm Agility Course (Advanced)"),
		Map.entry("wyrmadvanced", "Colossal Wyrm Agility Course (Advanced)"),
		Map.entry("wyrm advanced", "Colossal Wyrm Agility Course (Advanced)"),
		Map.entry("colossal advanced", "Colossal Wyrm Agility Course (Advanced)"),
		Map.entry("colossal wyrm advanced", "Colossal Wyrm Agility Course (Advanced)"),
		Map.entry("prif", "Prifddinas Agility Course"),
		Map.entry("prifddinas", "Prifddinas Agility Course"),
		Map.entry("shayb", "Shayzien Basic Agility Course"),
		Map.entry("sbac", "Shayzien Basic Agility Course"),
		Map.entry("shayzienbasic", "Shayzien Basic Agility Course"),
		Map.entry("shayzien basic", "Shayzien Basic Agility Course"),
		Map.entry("shaya", "Shayzien Advanced Agility Course"),
		Map.entry("saac", "Shayzien Advanced Agility Course"),
		Map.entry("shayadv", "Shayzien Advanced Agility Course"),
		Map.entry("shayadvanced", "Shayzien Advanced Agility Course"),
		Map.entry("shayzien advanced", "Shayzien Advanced Agility Course"),
		Map.entry("aa", "Ape Atoll Agility"),
		Map.entry("ape atoll", "Ape Atoll Agility"),
		Map.entry("draynor", "Draynor Village Rooftop"),
		Map.entry("draynor agility", "Draynor Village Rooftop"),
		Map.entry("al kharid", "Al Kharid Rooftop"),
		Map.entry("al kharid agility", "Al Kharid Rooftop"),
		Map.entry("al-kharid", "Al Kharid Rooftop"),
		Map.entry("al-kharid agility", "Al Kharid Rooftop"),
		Map.entry("alkharid", "Al Kharid Rooftop"),
		Map.entry("alkharid agility", "Al Kharid Rooftop"),
		Map.entry("varrock", "Varrock Rooftop"),
		Map.entry("varrock agility", "Varrock Rooftop"),
		Map.entry("canifis", "Canifis Rooftop"),
		Map.entry("canifis agility", "Canifis Rooftop"),
		Map.entry("fally", "Falador Rooftop"),
		Map.entry("fally agility", "Falador Rooftop"),
		Map.entry("falador", "Falador Rooftop"),
		Map.entry("falador agility", "Falador Rooftop"),
		Map.entry("seers", "Seers' Village Rooftop"),
		Map.entry("seers agility", "Seers' Village Rooftop"),
		Map.entry("seers village", "Seers' Village Rooftop"),
		Map.entry("seers village agility", "Seers' Village Rooftop"),
		Map.entry("seers'", "Seers' Village Rooftop"),
		Map.entry("seers' agility", "Seers' Village Rooftop"),
		Map.entry("seers' village", "Seers' Village Rooftop"),
		Map.entry("seers' village agility", "Seers' Village Rooftop"),
		Map.entry("seer's", "Seers' Village Rooftop"),
		Map.entry("seer's agility", "Seers' Village Rooftop"),
		Map.entry("seer's village", "Seers' Village Rooftop"),
		Map.entry("seer's village agility", "Seers' Village Rooftop"),
		Map.entry("pollnivneach", "Pollnivneach Rooftop"),
		Map.entry("pollnivneach agility", "Pollnivneach Rooftop"),
		Map.entry("rellekka", "Rellekka Rooftop"),
		Map.entry("rellekka agility", "Rellekka Rooftop"),
		Map.entry("ardy", "Ardougne Rooftop"),
		Map.entry("ardy agility", "Ardougne Rooftop"),
		Map.entry("ardy rooftop", "Ardougne Rooftop"),
		Map.entry("ardougne", "Ardougne Rooftop"),
		Map.entry("ardougne agility", "Ardougne Rooftop"),
		Map.entry("ap", "Agility Pyramid"),
		Map.entry("pyramid", "Agility Pyramid"),
		Map.entry("barb", "Barbarian Outpost"),
		Map.entry("barb outpost", "Barbarian Outpost"),
		Map.entry("brimhaven", "Agility Arena"),
		Map.entry("brimhaven agility", "Agility Arena"),
		Map.entry("dorg", "Dorgesh-Kaan Agility"),
		Map.entry("dorgesh kaan", "Dorgesh-Kaan Agility"),
		Map.entry("dorgesh-kaan", "Dorgesh-Kaan Agility"),
		Map.entry("gnome stronghold", "Gnome Stronghold Agility"),
		Map.entry("penguin", "Penguin Agility"),
		Map.entry("werewolf", "Werewolf Agility"),
		Map.entry("skullball", "Werewolf Skullball"),
		Map.entry("wildy", "Wilderness Agility"),
		Map.entry("wildy agility", "Wilderness Agility"),
		Map.entry("jad 1", "TzHaar-Ket-Rak's First Challenge"),
		Map.entry("jad 2", "TzHaar-Ket-Rak's Second Challenge"),
		Map.entry("jad 3", "TzHaar-Ket-Rak's Third Challenge"),
		Map.entry("jad 4", "TzHaar-Ket-Rak's Fourth Challenge"),
		Map.entry("jad 5", "TzHaar-Ket-Rak's Fifth Challenge"),
		Map.entry("jad 6", "TzHaar-Ket-Rak's Sixth Challenge"),
		Map.entry("gotr", "Guardians of the Rift"),
		Map.entry("runetodt", "Guardians of the Rift"),
		Map.entry("rifts closed", "Guardians of the Rift"),
		Map.entry("fishingtodt", "Tempoross"),
		Map.entry("fishtodt", "Tempoross"),
		Map.entry("phantom", "Phantom Muspah"),
		Map.entry("muspah", "Phantom Muspah"),
		Map.entry("pm", "Phantom Muspah"),
		Map.entry("the leviathan", "Leviathan"),
		Map.entry("levi", "Leviathan"),
		Map.entry("duke", "Duke Sucellus"),
		Map.entry("the whisperer", "Whisperer"),
		Map.entry("whisp", "Whisperer"),
		Map.entry("wisp", "Whisperer"),
		Map.entry("vard", "Vardorvis"),
		Map.entry("leviathan awakened", "Leviathan (awakened)"),
		Map.entry("the leviathan awakened", "Leviathan (awakened)"),
		Map.entry("levi awakened", "Leviathan (awakened)"),
		Map.entry("duke sucellus awakened", "Duke Sucellus (awakened)"),
		Map.entry("duke awakened", "Duke Sucellus (awakened)"),
		Map.entry("whisperer awakened", "Whisperer (awakened)"),
		Map.entry("the whisperer awakened", "Whisperer (awakened)"),
		Map.entry("whisp awakened", "Whisperer (awakened)"),
		Map.entry("wisp awakened", "Whisperer (awakened)"),
		Map.entry("vardorvis awakened", "Vardorvis (awakened)"),
		Map.entry("vard awakened", "Vardorvis (awakened)"),
		Map.entry("lunar chests", "Lunar Chest"),
		Map.entry("perilous moons", "Lunar Chest"),
		Map.entry("perilous moon", "Lunar Chest"),
		Map.entry("moons of peril", "Lunar Chest"),
		Map.entry("hunterrumour", "Hunter Rumours"),
		Map.entry("hunter contract", "Hunter Rumours"),
		Map.entry("hunter contracts", "Hunter Rumours"),
		Map.entry("hunter tasks", "Hunter Rumours"),
		Map.entry("hunter task", "Hunter Rumours"),
		Map.entry("rumours", "Hunter Rumours"),
		Map.entry("rumour", "Hunter Rumours"),
		Map.entry("sol", "Sol Heredit"),
		Map.entry("colo", "Sol Heredit"),
		Map.entry("colosseum", "Sol Heredit"),
		Map.entry("fortis colosseum", "Sol Heredit"),
		Map.entry("glory", "Colosseum Glory"),
		Map.entry("colo glory", "Colosseum Glory"),
		Map.entry("bird egg", "Bird's egg offerings"),
		Map.entry("bird eggs", "Bird's egg offerings"),
		Map.entry("bird's egg", "Bird's egg offerings"),
		Map.entry("bird's eggs", "Bird's egg offerings"),
		Map.entry("amox", "Amoxliatl"),
		Map.entry("the hueycoatl", "Hueycoatl"),
		Map.entry("huey", "Hueycoatl"),
		Map.entry("crystal chest", "crystal chest"),
		Map.entry("larran small chest", "Larran's small chest"),
		Map.entry("larran's small chest", "Larran's small chest"),
		Map.entry("larran chest", "Larran's big chest"),
		Map.entry("larran's chest", "Larran's big chest"),
		Map.entry("larran big chest", "Larran's big chest"),
		Map.entry("larran's big chest", "Larran's big chest"),
		Map.entry("brimstone chest", "Brimstone chest"),
		Map.entry("dom", "Doom of Mokhaiotl"),
		Map.entry("doom", "Doom of Mokhaiotl"));

	private BossAliases()
	{
	}

	static String resolve(String boss)
	{
		String alias = ALIASES.get(boss.toLowerCase(Locale.ENGLISH));
		return alias != null ? alias : capitalize(boss);
	}

	// Capitalize bosses to their standard format in osrs
	private static String capitalize(String value)
	{
		char[] chars = value.toCharArray();
		boolean capitalizeNext = true;
		for (int i = 0; i < chars.length; i++)
		{
			if (Character.isWhitespace(chars[i]))
			{
				capitalizeNext = true;
			}
			else if (capitalizeNext)
			{
				chars[i] = Character.toTitleCase(chars[i]);
				capitalizeNext = false;
			}
		}

		return new String(chars);
	}
}
